[package]
name = "mannot"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["ryuryu-ymj"]
license = "MIT"
description = "A package for highlighting and annotating in math blocks."
repository = "https://github.com/ryuryu-ymj/mannot"
keywords = ["highlight", "annotation", "math"]
categories = ["visualization", "layout"]
exclude = ["docs/*", "tests/*", "examples/*"]
